<a href="https://colab.research.google.com/github/umang0015/Ai-DataScience/blob/main/NLP/10AugSession1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# bag of words implementation using count vectorizer on a sample document
d1= "the cat sat on the mat"
d2= "the dog sat on the log"
d3= "the cat chased the dog"

In [ ]:
docs = set([d1,d2,d3])

In [ ]:
# build the document vocabulary
vocab = [w for d in docs for w in d.split()]
vocab = set(vocab)
vocab = sorted(vocab)
print(vocab)

['cat', 'chased', 'dog', 'log', 'mat', 'on', 'sat', 'the']

In [ ]:
# build a bow matrix
matrix = []
for d in docs:
    row=[]
    for w in vocab:
        row.append(d.count(w))
    matrix.append(row)
print(matrix)

[[0, 0, 1, 1, 0, 1, 1, 2], [1, 0, 0, 0, 1, 1, 1, 2], [1, 1, 1, 0, 0, 0, 0, 2]]

In [ ]:
# now implement bow on docs using built in count vectorizer
from sklearn.feature_extraction.text import CountVectorizer
cv  = CountVectorizer()
x = cv.fit_transform(docs)
print(x.toarray())
print(cv.get_feature_names_out())

[[0 0 1 1 0 1 1 2]
 [1 0 0 0 1 1 1 2]
 [1 1 1 0 0 0 0 2]]
['cat' 'chased' 'dog' 'log' 'mat' 'on' 'sat' 'the']

In [ ]:
# TFIDF implementation manual
d1= "the cat sat on the mat"
d2= "the dog sat on the log"
d3= "the cat chased the dog"
docs = [d1,d2,d3]

In [ ]:
N = len(docs)
tokens = [doc.split() for doc in docs]
print(tokens)

[['the', 'cat', 'sat', 'on', 'the', 'mat'], ['the', 'dog', 'sat', 'on', 'the', 'log'], ['the', 'cat', 'chased', 'the', 'dog']]

In [ ]:
# example term t
term ='mat'

In [ ]:
# calculate the TF for above word
for i ,toks in  enumerate(tokens):
  tf = toks.count(term)/len(toks)
  print('tf: ', tf)

tf:  0.16666666666666666
tf:  0.0
tf:  0.0

In [ ]:
# compute the df and idf for the given term
import math
dfreq = sum(1 for toks in tokens if term in toks)
idf = math.log(N/dfreq)+1
print('idf: ' , idf)

idf:  2.09861228866811

In [ ]:
# compute tf idf
for i , toks in enumerate(tokens):
  tf = toks.count(term)/len(toks)
  tfidf = tf*idf
  print('tfidf: ', tfidf)

tfidf:  0.3497687147780183
tfidf:  0.0
tfidf:  0.0

In [ ]:
# using sklearn to find tfidf
# by default tfidf it uses normalization thats why output is different in manual
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
x= tfidf.fit_transform(docs)
print(x.toarray())
print(tfidf.get_feature_names_out())
# display output as dataframe
import pandas as pd
df = pd.DataFrame(x.toarray(), columns=tfidf.get_feature_names_out())
df

[[0.37420726 0.         0.         0.         0.49203758 0.37420726
  0.37420726 0.58121064]
 [0.         0.         0.37420726 0.49203758 0.         0.37420726
  0.37420726 0.58121064]
 [0.40352536 0.53058735 0.40352536 0.         0.         0.
  0.         0.62674687]]
['cat' 'chased' 'dog' 'log' 'mat' 'on' 'sat' 'the']

,cat,chased,dog,log,mat,on,sat,the
0,0.374207,0.000000,0.000000,0.000000,0.492038,0.374207,0.374207,0.581211
1,0.000000,0.000000,0.374207,0.492038,0.000000,0.374207,0.374207,0.581211
2,0.403525,0.530587,0.403525,0.000000,0.000000,0.000000,0.000000,0.626747

In [ ]:
tfidf = TfidfVectorizer(smooth_idf=False, norm=None)
x= tfidf.fit_transform(docs)
import pandas as pd
df=pd.DataFrame(x.toarray() , columns=tfidf.get_feature_names_out())
df

        cat    chased       dog       log       mat        on       sat  the
0  1.405465  0.000000  0.000000  0.000000  2.098612  1.405465  1.405465  2.0
1  0.000000  0.000000  1.405465  2.098612  0.000000  1.405465  1.405465  2.0
2  1.405465  2.098612  1.405465  0.000000  0.000000  0.000000  0.000000  2.0

In [ ]:
# N grams helps capture some amount of context and meaning
# example: good and not good ,
# if unigram is applied their wont make any difference bn good and not good
# bigram can make difference
# also helps in handling compound names
# New Delhi, Ice Cream , machine learning
# usefull in predicting next words

### N grams helps capture some amount of context and meaning
### example: good and not good ,
### if unigram is applied their wont make any difference bn good and not good
### bigram can make difference
### also helps in handling compound names
### New Delhi, Ice Cream , machine learning
### usefull in predicting next words