<a href="https://colab.research.google.com/github/umang0015/Ai-DataScience/blob/main/8AugSpamtext.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Build a spam classification model
- first Upload data
- split into inputs and target
- preprocess
- create train test split
- build the model
- verify it

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/Models/SPAM text - SPAM text.csv')
df

     Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [ ]:
X = df['Message']
Y = df['Category']

In [ ]:
# check the no of categories in category column and frequency
df['Category'].value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [ ]:
# display sample message
print(df.Message[2])
print(df.Message[200])
print(df.Message[10])

Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's
Found it, ENC  &lt;#&gt; , where you at?
I'm gonna be home soon and i don't want to talk about this stuff anymore tonight, k? I've cried enough today.

In [ ]:
# next apply preprocessing onto the data
# import necessary libraries first
import nltk
import re
import string
import numpy as np
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize
# ml
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score , confusion_matrix , classification_report

In [ ]:
# download necessary corpus and docs
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [ ]:
# now applying preprocessing
# build preprocessing function
def text_process(text):
  # convert the text into lower
  text = text.lower()
  # remove the numbers using re
  text = re.sub(r'\d+','',text)
  # remove punctuation
  text = text.translate(str.maketrans('','',string.punctuation))
  # remove white spaces
  text = text.strip()

  # now tokenize the text
  tokens = text.split()
  # remove stopwords

  final_tokens = [word for word in tokens if word not in stopwords.words('english')]
  # applying stemming with porter stemmer
  ps = PorterStemmer()
  final_tokens = [ps.stem(word) for word in final_tokens]
  # join the tokens
  text = ' '.join(final_tokens)
  return text

In [ ]:
# now make call onto the text processing function by passing message
df['cleaned_message']= df['Message'].apply(text_process)
df.head(2)

,Category,Message,cleaned_message
0,ham,"Go until jurong point, crazy.. Available only ...",go jurong point crazi avail bugi n great world...
1,ham,Ok lar... Joking wif u oni...,ok lar joke wif u oni

In [ ]:
# apply countvectorizer(Bow ) onto the cleaned message
from sklearn.feature_extraction.text import CountVectorizer , TfidfVectorizer
BoW_vect = CountVectorizer()
X1 =BoW_vect.fit_transform(df['cleaned_message'])
Y1 =df['Category']

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vect = TfidfVectorizer()
X2 = tfidf_vect.fit_transform(df['cleaned_message'])
Y2 =df['Category']

In [ ]:
# split the training set start with X1 , Y1
X_train , X_test , y_train , y_test = train_test_split(X1,Y1,test_size=0.2,random_state=42)

In [ ]:
# build the classification model using logistic regression
LRC = LogisticRegression()
LRC.fit(X_train , y_train)

LogisticRegression()

In [ ]:
# test on test dataset
y_pred= LRC.predict(X_test)

In [ ]:
# compute accuracy score , confusion matrix
accuracy_score(y_test,y_pred)

0.9829596412556054

In [ ]:
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[965   1]
 [ 18 131]]

In [ ]:
965/966

0.9989648033126294

In [ ]:
131/149

0.8791946308724832

In [ ]:
# build the model using tfidf vectors
X_train , X_test , y_train , y_test = train_test_split(X2,Y2,test_size=0.2,random_state=42)
LRC.fit(X_train , y_train)
y_pred= LRC.predict(X_test)
accuracy_score(y_test,y_pred)
confusion_matrix(y_test,y_pred)

array([[965,   1],
       [ 46, 103]])

In [ ]:
# train both sets using naive bayes for tfidf
from sklearn.naive_bayes import MultinomialNB
MNB= MultinomialNB()
MNB.fit(X_train , y_train)
y_pred= MNB.predict(X_test)
print(accuracy_score(y_test,y_pred))
confusion_matrix(y_test,y_pred)

0.9668161434977578

array([[965,   1],
       [ 36, 113]])

In [ ]:
# now build naive bayes on BOW data
X_train , X_test , y_train , y_test = train_test_split(X1,Y1,test_size=0.2,random_state=42)
MNB.fit(X_train , y_train)
y_pred= MNB.predict(X_test)
print(accuracy_score(y_test,y_pred))

confusion_matrix(y_test,y_pred)

0.9713004484304932

array([[943,  23],
       [  9, 140]])

In [ ]:
!pip install gensim

Collecting gensim
  Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from gensim) (2.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (8.0.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim) (2.2.2)
Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 46.1 MB/s eta 0:00:00
Installing collected packages: gensim
Successfully installed gensim-4.4.0

In [ ]:
# now applying wordvec inplace of tfidf/BOW
import gensim
from gensim.models import Word2Vec

In [ ]:
df['tokens'] =df['cleaned_message'].apply(lambda x : x.split())
df['tokens'].head()

0    [go, jurong, point, crazi, avail, bugi, n, gre...
1                         [ok, lar, joke, wif, u, oni]
2    [free, entri, wkli, comp, win, fa, cup, final,...
3        [u, dun, say, earli, hor, u, c, alreadi, say]
4    [nah, dont, think, goe, usf, live, around, tho...
Name: tokens, dtype: object

In [ ]:
# tokenize
# pass to word2vec for training
# next pass the embedding to the ml model
# validate the results

In [ ]:
w2v_model = Word2Vec(df['tokens'], vector_size=100 ,window=5 , min_count=1 , workers=4 )
print('vocab size' , len(w2v_model.wv))
print('vector size' ,w2v_model.wv.vector_size)

vocab size 7239
vector size 100

In [ ]:
# word2vec gives one vector per word , we need it for vector for a message(each row)
# define function which converts a vector to a word to vector for a message
def get_doc_vector(tokens , model):
  vectors = [model.wv[word] for word in tokens if word in model.wv]
  if vectors:
    return np.mean(vectors,axis=0)
  else:
    return np.zeros(model.wv.vector_size)
# call the function
X3 = np.array([get_doc_vector(tokens , w2v_model) for tokens in df['tokens']])
Y3 = df['Category']

In [ ]:
# split with train test split
X_train , X_test , y_train , y_test = train_test_split(X3,Y3,test_size=0.2,random_state=42)

In [ ]:
# train on logistic regression
LRC = LogisticRegression()
LRC.fit(X_train , y_train)
y_pred= LRC.predict(X_test)
print(accuracy_score(y_test,y_pred))
confusion_matrix(y_test,y_pred)

0.8708520179372198

array([[966,   0],
       [144,   5]])

In [ ]:
from sklearn.naive_bayes import GaussianNB

# trying with naive bayes (GaussianNB suitable for continuous, potentially negative data)
GB = GaussianNB()
GB.fit(X_train , y_train)
y_pred = GB.predict(X_test)
print(accuracy_score(y_test,y_pred))
confusion_matrix(y_test,y_pred)

0.4923766816143498

array([[434, 532],
       [ 34, 115]])