<a href="https://colab.research.google.com/github/umang0015/Ai-DataScience/blob/main/29JulyPractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [20]:
import warnings
warnings.filterwarnings('ignore')

In [21]:
data = '/content/pulsar_stars - pulsar_stars.csv'
df = pd.read_csv(data)

In [22]:
df.head()

,Mean of the integrated profile,Standard deviation of the integrated profile,Excess kurtosis of the integrated profile,Skewness of the integrated profile,Mean of the DM-SNR curve,Standard deviation of the DM-SNR curve,Excess kurtosis of the DM-SNR curve,Skewness of the DM-SNR curve,target_class
0,140.562500,55.683782,-0.234571,-0.699648,3.199833,19.110426,7.975532,74.242225,0
1,102.507812,58.882430,0.465318,-0.515088,1.677258,14.860146,10.576487,127.393580,0
2,103.015625,39.341649,0.323328,1.051164,3.121237,21.744669,7.735822,63.171909,0
3,136.750000,57.178449,-0.068415,-0.636238,3.642977,20.959280,6.896499,53.593661,0
4,88.726562,40.672225,0.600866,1.123492,1.178930,11.468720,14.269573,252.567306,0

In [23]:
df.columns

Index(['Mean of the integrated profile',
       'Standard deviation of the integrated profile',
       'Excess kurtosis of the integrated profile',
       'Skewness of the integrated profile', 'Mean of the DM-SNR curve',
       'Standard deviation of the DM-SNR curve',
       'Excess kurtosis of the DM-SNR curve', 'Skewness of the DM-SNR curve',
       'target_class'],
      dtype='object')

In [24]:
df.columns= df.columns.str.strip()
# leading spaces are removed from the column name

In [25]:
df.columns

Index(['Mean of the integrated profile',
       'Standard deviation of the integrated profile',
       'Excess kurtosis of the integrated profile',
       'Skewness of the integrated profile', 'Mean of the DM-SNR curve',
       'Standard deviation of the DM-SNR curve',
       'Excess kurtosis of the DM-SNR curve', 'Skewness of the DM-SNR curve',
       'target_class'],
      dtype='object')

In [26]:
df.columns = ['IP Mean' , 'IP Sd', 'IP Kurtosis' , 'IP Skewness' , 'DM-SNR Mean' , 'DM-SNR Sd', 'DM-SNR Kurtosis' , 'DM-SNR Skewness' , 'target_class']

In [28]:
df.columns
# column names are shortened IP Stands for Integrated

Index(['IP Mean', 'IP Sd', 'IP Kurtosis', 'IP Skewness', 'DM-SNR Mean',
       'DM-SNR Sd', 'DM-SNR Kurtosis', 'DM-SNR Skewness', 'target_class'],
      dtype='object')

In [29]:
df['target_class'].value_counts()

target_class
0    16259
1     1639
Name: count, dtype: int64

In [30]:
df.info()
# no missing values in variables

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17898 entries, 0 to 17897
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   IP Mean          17898 non-null  float64
 1   IP Sd            17898 non-null  float64
 2   IP Kurtosis      17898 non-null  float64
 3   IP Skewness      17898 non-null  float64
 4   DM-SNR Mean      17898 non-null  float64
 5   DM-SNR Sd        17898 non-null  float64
 6   DM-SNR Kurtosis  17898 non-null  float64
 7   DM-SNR Skewness  17898 non-null  float64
 8   target_class     17898 non-null  int64
dtypes: float64(8), int64(1)
memory usage: 1.2 MB

In [31]:
X = df.drop(['target_class'],axis=1)
y = df['target_class']

In [32]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [33]:
# shape of Xtrain and xtest
X_train.shape
X_test.shape

(3580, 8)

In [34]:
cols = X_train.columns

In [35]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [36]:
X_train = pd.DataFrame(X_train, columns=[cols])
X_test = pd.DataFrame(X_test, columns=[cols])

In [37]:
X_train.describe()

,IP Mean,IP Sd,IP Kurtosis,IP Skewness,DM-SNR Mean,DM-SNR Sd,DM-SNR Kurtosis,DM-SNR Skewness
count,1.431800e+04,1.431800e+04,1.431800e+04,1.431800e+04,1.431800e+04,1.431800e+04,1.431800e+04,1.431800e+04
mean,1.908113e-16,-6.550610e-16,1.042143e-17,3.870815e-17,-8.734147e-17,-1.617802e-16,-1.513588e-17,1.122785e-16
std,1.000035e+00,1.000035e+00,1.000035e+00,1.000035e+00,1.000035e+00,1.000035e+00,1.000035e+00,1.000035e+00
min,-4.035499e+00,-3.181033e+00,-2.185946e+00,-5.744051e-01,-4.239001e-01,-9.733707e-01,-2.455649e+00,-1.003411e+00
25%,-3.896291e-01,-6.069473e-01,-4.256221e-01,-3.188054e-01,-3.664918e-01,-6.125457e-01,-5.641035e-01,-6.627590e-01
50%,1.587461e-01,5.846646e-02,-2.453172e-01,-2.578142e-01,-3.372294e-01,-4.067482e-01,3.170446e-02,-2.059136e-01
75%,6.267059e-01,6.501017e-01,-1.001238e-02,-1.419621e-01,-2.463724e-01,1.078934e-01,5.362759e-01,3.256217e-01
max,3.151882e+00,7.621116e+00,7.008906e+00,1.054430e+01,7.025568e+00,4.292181e+00,5.818557e+00,1.024613e+01

In [38]:
X

,IP Mean,IP Sd,IP Kurtosis,IP Skewness,DM-SNR Mean,DM-SNR Sd,DM-SNR Kurtosis,DM-SNR Skewness
0,0.377102,0.186432,-0.213043,-0.303767,-0.162367,0.445494,-0.764988,-0.762900
1,0.219585,0.311963,-0.268826,-0.252348,-0.329485,-0.502235,-0.023698,-0.184681
2,-1.699540,1.699078,1.248413,0.094819,2.027133,2.764156,-1.688753,-0.993425
3,-0.676429,-1.788178,0.157113,0.176569,-0.304813,-0.216554,-0.183040,-0.408275
4,-0.443917,0.302114,-0.016524,-0.250519,-0.374223,-0.677774,0.643273,0.491991
...,...,...,...,...,...,...,...,...
14313,-1.647436,-1.586048,1.361247,0.891188,-0.298618,-0.075206,-0.279452,-0.500016
14314,0.813212,0.376411,-0.473322,-0.317854,-0.403583,-0.819431,1.893857,2.241049
14315,0.859895,1.300484,-0.538831,-0.343197,-0.385274,-0.704001,0.864545,0.726348
14316,-0.489094,0.326939,-0.163262,-0.265837,-0.356807,-0.522955,0.427540,0.172991
14317,-0.185504,-0.655460,-0.062179,-0.197697,-0.326778,-0.333251,-0.212588,-0.430370

In [40]:
# import SVC Classifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
svc = SVC()

svc.fit(X_train, y_train)
y_pred = svc.predict(X_test)
accuracy_score(y_test, y_pred)
print('Model accuracy scre with default hyperparameters: {0:0.4f}'.format(accuracy_score(y_test,y_pred)))

Model accuracy scre with default hyperparameters: 0.9827

In [41]:
svc = SVC(C=100.0)

svc.fit(X_train, y_train)
y_pred = svc.predict(X_test)
print('Model accuracy score with rbf kernel and C=100.0 : {0:0.4f}'.format(accuracy_score(y_test,y_pred)))

Model accuracy score with rbf kernel and C=100.0 : 0.9832

In [42]:
linear_svc = SVC(kernel='linear', C=1.0)

linear_svc.fit(X_train, y_train)
y_pred_test = linear_svc.predict(X_test)
print('Model accuracy score with linear kernel and C=1.0 : {0:0.4f}'.format(accuracy_score(y_test,y_pred_test)))

Model accuracy score with linear kernel and C=1.0 : 0.9830

In [43]:
poly_svc = SVC(kernel='poly', C=1.0)

poly_svc.fit(X_train, y_train)
y_pred_test = poly_svc.predict(X_test)
print('Model accuracy score with polynomial kernel and C=1.0 : {0:0.4f}'.format(accuracy_score(y_test,y_pred_test)))

Model accuracy score with polynomial kernel and C=1.0 : 0.9807